### ISSUE TITLE
Question over the command inter=wlan1

### ISSUE THREAD

**Issue by Tarantyev** [ArieLevs/Raspberry-WiFi-Repeater#15]
Hi
I've successfully used the guide to create a wifi repeater on my Rpi4 bridging between two USB wifi dongles set up as wlan0 and 1, thank you so much for taking the time to make this available.

I have a question though about one step, where it says run "inter=wlan1". Whilst I did this, the command was accepted, what is this actually doing? I can't seem to find a command called "inter".
Thanks so much
T

**Comment by ArieLevs** [comment]
Hi @Tarantyev 

the `inter=wlan1` is actually not a command, but a variable assignment (shortcut for `interface`).

So for example instead of executing
```
inter=wlan1
sudo iptables -t nat -A POSTROUTING -o ${inter} -j MASQUERADE
```

you could also do
```
some_var_name=wlan56
sudo iptables -t nat -A POSTROUTING -o ${some_var_name} -j MASQUERADE
```
or just
```
sudo iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
```

I've used a variable so it will be easier for users to switch between different interfaces without the need of documenting the full command twice.

And thank you for this feedback!
